export const ADMIN_PERMISSIONS = [
  { label: "Dashboard", value: "/admin/dashboard" },
  { label: "Courses Management", value: "/admin/courses-management" },
  { label: "Course Builder", value: "/admin/courses-management/builder" },
  { label: "Attendance & Progress", value: "/admin/courses-management/attendance" },
  { label: "Waiting List", value: "/admin/courses-management/waiting-list" },
  { label: "Email Templates", value: "/admin/email-templates" },
  { label: "Student Attendence", value: "/admin/attendance-list" },
  { label: "User Management", value: "/admin/user-management" },
  { label: "Add User Management", value: "/admin/user-management/add-user" },
  { label: "User Detailed View", value: "/admin/user-management/users-details" },
  { label: "Edit User", value: "/admin/user-management/edit-user" },
  { label: "Class Scheduling", value: "/admin/class-scheduling" },
  { label: "Reschedule Requests", value: "/admin/reschedule-requests" },
  { label: "Announcements", value: "/admin/announcements" },
  { label: "Payments & Refunds", value: "/admin/payments" },
  { label: "Support", value: "/admin/tickets" },
  { label: "Analytics", value: "/admin/analytics" },
  { label: "View Contact Forms", value: "/admin/contact-forms" },
  { label: "User Appointment", value: "/admin/user-appointment" },
  { label: "All Events & Retreats", value: "/admin/events-retreats" },
  { label: "Add/Edit Events & Retreats", value: "/admin/events-retreats/manage" },
  { label: "Site Content", value: "/admin/site-content" },
  { label: "Site Settings", value: "/admin/site-settings" },
  { label: "SEO Settings", value: "/admin/seo-settings" },
  { label: "Notifications", value: "/admin/notifications" },
  { label: "Message Center Or Chat", value: "/admin/help/messages" },
  { label: "Teacher & Student Chat", value: "/admin/help/chat" },
  { label: "Reviews", value: "/admin/help/reviews" },
  { label: "FAQs", value: "/admin/faqs" },
  { label: "User Logs / Activity", value: "/admin/user-logs" },
];
